### PR TITLE
Support GHC 8.8

### PR DESCRIPTION
**Pull request by fumieval**
Pardon an automatically-posted pull request; this is a part of [Operation Vanguard](https://github.com/haskell-vanguard/haskell-vanguard). Note that this does not guarantee that tests and benchmarks are buildable.

### CODE REVIEW

**Comment by jacobstanley** [comment]
Happy to merge this but would like a bit more confidence that it actually works.

Longer term it would make sense to get an AppVeyor build going to check windows compatibility, I don't really have easy access to a windows box (ironic I know) so it's a bit hard for me to check this myself.

**Comment by mrkkrp** [comment]
It looks like the library doesn't build on Windows with GHC 8.8.1:

https://ci.appveyor.com/project/mrkkrp/path-io/builds/27688758/job/ya74br66r603wlnr#L328

Is there a chance we'll get this library to work? It's not about just the library itself, it's blocking at least 79 other packages:

https://packdeps.haskellers.com/reverse/unix-compat

**Comment by mrkkrp** [comment]
Ping.

**Comment by RyanGlScott** [comment]
To be clear, the build log in https://ci.appveyor.com/project/mrkkrp/path-io/builds/27688758/job/ya74br66r603wlnr#L328 isn't testing this PR, but rather showing a separate project failing to build due to `cabal-install` picking a build plan with an ancient version of `unix-compat` due to the upper version bounds on `time` in `unix-compat-0.5.2` (the current version).

I do have access to a Windows machine, and I was able to successfully build `unix-compat` after applying the changes in this PR. There are no test suites in `unix-compat.cabal` for me to try, but I was also able to run the `main` function in `tests/mkstemp.hs` with this PR.

**Comment by jneira** [comment]
Hi, i've hit the lack of ghc-8.8.1 support trying to build [haskell-ide-engine with ghc-8.8.1 support](https://github.com/haskell/haskell-ide-engine/pull/1482)

In case may help I've also tried to build master and this pr in my windows 10:
* master
```
PS D:\dev\ws\haskell> git clone https://github.com/jacobstanley/unix-compat    
Cloning into 'unix-compat'...
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (8/8), done.
Receiving objects: 100% (590/590), 92.06 KiB | 41.00 KiB/s, done.
Resolving deltas: 100% (312/312), done.
remote: Total 590 (delta 2), reused 7 (delta 2), pack-reused 580
PS D:\dev\ws\haskell> cd .\unix-compat\
PS D:\dev\ws\haskell\unix-compat> cabal build -w ghc-8.8.1
Resolving dependencies...
cabal.exe: Could not resolve dependencies:
[__0] trying: unix-compat-0.5.2 (user goal)
[__1] trying: unix-compat:-old-time
[__2] next goal: time (dependency of unix-compat -old-time)
[__2] rejecting: time-1.9.3/installed-1.9..., time-1.9.3, time-1.9.2,
time-1.9.1, time-1.9 (conflict: unix-compat -old-time => time>=1.0 && <1.9)
[__2] trying: time-1.8.0.4
[__3] next goal: deepseq (dependency of time)
[__3] rejecting: deepseq-1.4.4.0/installed-1.4... (conflict: time => base>=4.7
&& <4.13, deepseq => base==4.13.0.0/installed-4.1...)
[__3] trying: deepseq-1.4.4.0
[__4] next goal: array (dependency of deepseq)
[__4] rejecting: array-0.5.4.0/installed-0.5... (conflict: time => base>=4.7
&& <4.13, array => base==4.13.0.0/installed-4.1...)
[__4] trying: array-0.5.4.0
[__5] next goal: directory (dependency of unix-compat +/-old-time)
[__5] rejecting: directory-1.3.3.2/installed-1.3... (conflict: time =>
base>=4.7 && <4.13, directory => base==4.13.0.0/installed-4.1...)
[__5] trying: directory-1.3.5.0
[__6] next goal: base (dependency of unix-compat)
[__6] rejecting: base-4.13.0.0/installed-4.1... (conflict: time => base>=4.7
&& <4.13)
[__6] rejecting: base-4.12.0.0, base-4.11.1.0, base-4.11.0.0, base-4.10.1.0,
base-4.10.0.0, base-4.9.1.0, base-4.9.0.0, base-4.8.2.0, base-4.8.1.0,
base-4.8.0.0, base-4.7.0.2, base-4.7.0.1, base-4.7.0.0, base-4.6.0.1,
base-4.6.0.0, base-4.5.1.0, base-4.5.0.0, base-4.4.1.0, base-4.4.0.0,
base-4.3.1.0, base-4.3.0.0, base-4.2.0.2, base-4.2.0.1, base-4.2.0.0,
base-4.1.0.0, base-4.0.0.0, base-3.0.3.2, base-3.0.3.1 (constraint from
non-upgradeable package requires installed instance)
[__6] fail (backjumping, conflict set: base, time, unix-compat)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: array, deepseq, base, time, directory,
unix-compat, unix-compat:old-time
Try running with --minimize-conflict-set to improve the error message.
```
* this pr:
```
PS D:\dev\ws\haskell\unix-compat> git fetch origin pull/42/head:ghc-8.8.1
remote: Enumerating objects: 2, done.
remote: Counting objects: 100% (2/2), done.
remote: Total 3 (delta 2), reused 2 (delta 2), pack-reused 1
Unpacking objects: 100% (3/3), done.
From https://github.com/jacobstanley/unix-compat
 * [new ref]         refs/pull/42/head -> ghc-8.8.1
PS D:\dev\ws\haskell\unix-compat> git checkout ghc-8.8.1
Switched to branch 'ghc-8.8.1'
PS D:\dev\ws\haskell\unix-compat> cabal build -w ghc-8.8.1
Resolving dependencies...
Build profile: -w ghc-8.8.1 -O1
In order, the following will be built (use -v for more details):
 - unix-compat-0.5.0.1 (lib:unix-compat) (first run)
Configuring unix-compat-0.5.0.1...
Preprocessing library for unix-compat-0.5.0.1..
Building library for unix-compat-0.5.0.1..
[1 of 9] Compiling System.PosixCompat.Internal.Time ( src\System\PosixCompat\Internal\Time.hs, 
.......
[9 of 9] Compiling System.PosixCompat ( src\System\PosixCompat.hs, D:\\dev\ws\haskell\unix-compat\dist-newstyle\build\x86_64-windows\ghc-8.8.1\unix-compat-0.5.0.1\build\System\PosixCompat.o )
```
Running `cabal build -w ghc-8.8.1 --allow-newer "time"` also works.

**Comment by jacobstanley** [comment]
Have updated the package metadata on hackage so the currently published version should also work.

**Comment by jacobstanley** [comment]
@jneira thanks for verifying

Ideally we'd just have a windows CI for this. I just don't have the time at the moment.

**Comment by jneira** [comment]
@jacobstanley wow thanks a lot!

**Pull request merged**
